// apps/shell/components/atlas/wrapped.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import { DEFAULT_START, MINUTE } from '@portfolio/world';
import { ZLink } from '@/components/zone-link';
import { Layer, closeLayers, openLayer, useDemoState, useParams } from '@/components/overlay';
import { useSimNow } from '@/lib/world';
import { funnel, pipelineTimeline, skills, velocity } from '@/lib/atlas';
import { AtlasHeader } from './header';

const FRAME_MS = 6000;
const replays = [52, 58, 61, 66, 70, 74];
const top = [...skills].sort((a, b) => b[1] - a[1])[0]!;
const onsites = funnel.find(([stage]) => stage === 'Onsite')![1];
const offers = funnel.find(([stage]) => stage === 'Offer')![1];

type Card = { id: string; tone: string; kicker: string; title: string; body: React.ReactNode };

function useCards(few: boolean, screensToday: number): Card[] {
  const sessions = few ? 3 : velocity.reduce((sum, [, count]) => sum + count, 0);
  const maxMonth = Math.max(...velocity.map(([, count]) => count));
  if (few) {
    return [
      { id: 'start', tone: 'mint', kicker: 'Atlas Wrapped · 2026', title: 'You started.', body: <p className="aw-big">3 sessions</p> },
      { id: 'next', tone: 'indigo', kicker: 'What unlocks the full recap', title: 'Two more and we can see your trend.', body: <p>Five sessions is enough to chart growth, find your top skill and your most replayed prompt. Your next 20-minute drill is ready.</p> },
      { id: 'go', tone: 'amber', kicker: 'Keep going', title: 'Pick up where you left off.', body: <ZLink className="aw-cta" href="/atlas/arena/mix/today">Open today&apos;s mix</ZLink> }
    ];
  }
  return [
    { id: 'sessions', tone: 'mint', kicker: 'Atlas Wrapped · 2026', title: `You practiced ${sessions} times.`, body: (
      <div className="aw-bars" role="img" aria-label={`Sessions per month: ${velocity.map(([month, count]) => `${month} ${count}`).join(', ')}`}>
        {velocity.map(([month, count], index) => <span key={month} style={{ '--h': count / maxMonth, '--i': index } as React.CSSProperties}><i /><b>{count}</b><small>{month}</small></span>)}
      </div>
    ) },
    { id: 'skill', tone: 'indigo', kicker: 'Your top skill', title: `${top[0]}, ${top[1]}/100.`, body: (
      <div className="aw-ring" role="img" aria-label={`${top[0]} scored ${top[1]} of 100`}>
        <svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="50" className="track" /><circle cx="60" cy="60" r="50" className="fill" style={{ strokeDasharray: `${(top[1] / 100) * 314} 314` }} /></svg>
        <b>{top[1]}</b>
      </div>
    ) },
    { id: 'replay', tone: 'amber', kicker: 'Most replayed prompt', title: 'Design a payments ledger, 6 times.', body: (
      <svg className="aw-line" viewBox="0 0 300 120" role="img" aria-label={`Score by attempt: ${replays.join(', ')}`}>
        <polyline points={replays.map((score, index) => `${20 + index * 52},${110 - (score - 45) * 3}`).join(' ')} pathLength={1} />
        {replays.map((score, index) => <text key={index} x={20 + index * 52} y={100 - (score - 45) * 3}>{score}</text>)}
      </svg>
    ) },
    { id: 'outcomes', tone: 'coral', kicker: 'Where it took you', title: `${onsites} onsites, ${offers} offer.`, body: (
      <ul className="aw-outcomes">
        <li><b>{funnel[1][1]}</b> applied</li><li><b>{funnel[2][1]}</b> screens</li><li><b>{onsites}</b> onsites</li><li><b>{offers}</b> offer</li>
        {screensToday > 0 && <li className="aw-live"><b>+{screensToday}</b> {screensToday === 1 ? 'screen' : 'screens'} booked today</li>}
      </ul>
    ) },
    { id: 'share', tone: 'ink', kicker: 'That was your year', title: 'Share it without sharing your business.', body: (
      <div className="aw-share">
        <p>The share image leaves out company names and salary. Only your practice, your top skill and your outcome counts.</p>
        <button type="button" className="aw-cta" onClick={() => openLayer({ modal: 'share' })}>Share your recap</button>
      </div>
    ) }
  ];
}

/** Privacy-safe share image, drawn client-side: counts only, no company names, no salary. */
function ShareModal({ few }: { few: boolean }) {
  const canvas = useRef<HTMLCanvasElement>(null);
  const [url, setUrl] = useState<string | null>(null);
  useEffect(() => {
    const node = canvas.current;
    if (!node) return;
    const context = node.getContext('2d');
    if (!context) return;
    const css = getComputedStyle(document.documentElement);
    const token = (name: string) => css.getPropertyValue(name).trim() || '#000';
    const display = css.getPropertyValue('--font-display').trim();
    const gradient = context.createLinearGradient(0, 0, 1080, 1350);
    gradient.addColorStop(0, token('--accent'));
    gradient.addColorStop(1, token('--accent-2'));
    context.fillStyle = gradient;
    context.fillRect(0, 0, 1080, 1350);
    context.fillStyle = token('--accent-ink');
    context.font = `600 44px ${display}`;
    context.fillText('ATLAS WRAPPED · 2026', 80, 140);
    context.font = `700 150px ${display}`;
    const lines = few ? [['3', 'sessions to start']] : [[String(velocity.reduce((sum, [, count]) => sum + count, 0)), 'practice sessions'], [String(top[1]), `top skill · ${top[0]}`], [`${onsites} · ${offers}`, 'onsites · offer']];
    lines.forEach(([big, small], index) => {
      context.font = `700 150px ${display}`;
      context.fillText(big!, 80, 420 + index * 300);
      context.font = `500 44px ${display}`;
      context.fillText(small!, 80, 490 + index * 300);
    });
    context.font = `500 32px ${display}`;
    context.fillText('Company names and salary are never included.', 80, 1270);
    node.toBlob((blob) => blob && setUrl(URL.createObjectURL(blob)), 'image/png');
  }, [few]);
  useEffect(() => () => { if (url) URL.revokeObjectURL(url); }, [url]);
  return (
    <Layer kind="modal" title="Share your recap" eyebrow="Privacy-safe image · 1080 × 1350" onClose={() => closeLayers(['modal'])} width={520} anchor="aw-share-modal"
      footer={<>{url ? <a className="at-btn primary" href={url} download="atlas-wrapped-2026.png">Download image</a> : <span className="at-muted">Rendering…</span>}<button type="button" className="at-btn" onClick={() => closeLayers(['modal'])}>Done</button></>}>
      <canvas ref={canvas} width={1080} height={1350} className="aw-canvas" role="img" aria-label="Share image: practice sessions, top skill and outcome counts, with no company names or salary" />
      <ul className="aw-privacy">
        <li><span aria-hidden="true">✓</span> Practice counts and scores</li>
        <li><span aria-hidden="true">✕</span> Company names are left out</li>
        <li><span aria-hidden="true">✕</span> Salary and offer amounts are left out</li>
      </ul>
    </Layer>
  );
}

export function AtlasWrapped() {
  const state = useDemoState();
  const params = useParams();
  const now = useSimNow(5000) ?? DEFAULT_START;
  const few = state === 'empty';
  const screensToday = pipelineTimeline.filter((item) => item.stage === 'screen' && now >= DEFAULT_START + item.afterMinutes * MINUTE).length;
  const cards = useCards(few, screensToday);
  const [index, setIndex] = useState(0);
  const [paused, setPaused] = useState(false);
  const [held, setHeld] = useState(false);
  const [reduce, setReduce] = useState(false);
  const stopped = paused || held || reduce || params.get('modal') === 'share';

  useEffect(() => setReduce(matchMedia('(prefers-reduced-motion: reduce)').matches), []);
  useEffect(() => { if (index >= cards.length) setIndex(cards.length - 1); }, [cards.length, index]);
  useEffect(() => {
    if (stopped || index >= cards.length - 1) return;
    const timer = window.setTimeout(() => setIndex(index + 1), FRAME_MS);
    return () => window.clearTimeout(timer);
  }, [index, stopped, cards.length]);
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if (params.get('modal')) return;
      if (event.key === 'ArrowRight') setIndex((value) => Math.min(cards.length - 1, value + 1));
      if (event.key === 'ArrowLeft') setIndex((value) => Math.max(0, value - 1));
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [cards.length, params]);

  const card = cards[Math.min(index, cards.length - 1)]!;
  return (
    <>
      <AtlasHeader active="Arena" />
      <main className="aw" data-anchor="aw-main">
        <h1 className="visually-hidden">Atlas Wrapped</h1>
        <section className={`aw-story t-${card.tone}`} aria-roledescription="story" aria-label={`Card ${index + 1} of ${cards.length}`} data-anchor="aw-story">
          <div className="aw-bars-top" aria-hidden="true">
            {cards.map((item, position) => <span key={item.id}><i className={position < index ? 'done' : position === index ? (stopped ? 'hold' : 'now') : ''} style={{ animationDuration: `${FRAME_MS}ms` }} /></span>)}
          </div>
          <div className="aw-card" key={card.id} aria-live="polite">
            <span className="aw-kicker">{card.kicker}</span>
            <h2>{card.title}</h2>
            <div className="aw-body">{card.body}</div>
          </div>
          <button type="button" className="aw-hit prev" aria-label="Previous card" onClick={() => setIndex(Math.max(0, index - 1))}
            onPointerDown={() => setHeld(true)} onPointerUp={() => setHeld(false)} onPointerLeave={() => setHeld(false)} />
          <button type="button" className="aw-hit next" aria-label="Next card" onClick={() => setIndex(Math.min(cards.length - 1, index + 1))}
            onPointerDown={() => setHeld(true)} onPointerUp={() => setHeld(false)} onPointerLeave={() => setHeld(false)} />
          <div className="aw-controls">
            <button type="button" className="aw-pause" aria-pressed={paused} onClick={() => setPaused(!paused)} data-anchor="aw-pause">{paused ? 'Play' : 'Pause'}</button>
            <span>{index + 1} / {cards.length}</span>
            <button type="button" className="aw-pause" onClick={() => openLayer({ modal: 'share' })} data-anchor="aw-share-btn">Share</button>
          </div>
        </section>
      </main>
      {params.get('modal') === 'share' && <ShareModal few={few} />}
    </>
  );
}

// apps/pulse/src/routes/distribution/campaigns/afterglow/wrapped/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { base } from '$app/paths';
  import { view } from '$lib/view.svelte';
  import { live } from '$lib/world.svelte';
  import { params } from '$lib/params.svelte';
  import Layer from '$lib/Layer.svelte';
  import { usd } from '$lib/wallet';

  const FRAME_MS = 6000;
  const early = $derived(view.state === 'empty');
  const views = $derived(18_400_000 + Math.floor(live.elapsed * 42));
  const earnings = 6_380.25;
  const stops = [
    { city: 'Seoul', at: 'Day 1 · 21:40 KST', views: '9.1M', x: 70, y: 40 },
    { city: 'Tokyo', at: 'Day 2 · 08:15 JST', views: '5.8M', x: 190, y: 70 },
    { city: 'LA', at: 'Day 3 · 19:00 PT', views: '3.5M', x: 60, y: 150 }
  ];
  const cards = ['views', 'moment', 'travel', 'earnings'] as const;
  const tones = { views: 'pink', moment: 'cyan', travel: 'gold', earnings: 'ink' } as const;

  let index = $state(0);
  let paused = $state(false);
  let held = $state(false);
  let reduce = $state(false);
  let revealed = $state(false);
  let sent = $state(false);
  let deckUrl = $state<string | null>(null);
  onMount(() => { reduce = matchMedia('(prefers-reduced-motion: reduce)').matches; });

  const stopped = $derived(paused || held || reduce || Boolean(params.get('share')));
  $effect(() => {
    if (stopped || early || index >= cards.length - 1) return;
    const timer = setTimeout(() => (index += 1), FRAME_MS);
    return () => clearTimeout(timer);
  });
  function key(event: KeyboardEvent) {
    if (params.get('share')) return;
    if (event.key === 'ArrowRight') index = Math.min(cards.length - 1, index + 1);
    if (event.key === 'ArrowLeft') index = Math.max(0, index - 1);
  }

  /** "Export as deck": four slides drawn on one canvas, client-side, as a PNG (no upload). */
  function exportDeck() {
    const canvas = document.createElement('canvas');
    canvas.width = 1600;
    canvas.height = 900;
    const context = canvas.getContext('2d')!;
    const css = getComputedStyle(document.documentElement);
    const token = (name: string) => css.getPropertyValue(name).trim();
    const font = css.getPropertyValue('--font-display').trim();
    const tiles: Array<[string, string, string]> = [
      ['--accent', `${(views / 1_000_000).toFixed(1)}M views`, 'Afterglow · 7 days'],
      ['--ai', '0:24 fan edit', 'posted by 12 pages'],
      ['--warn', 'Seoul → Tokyo → LA', '9.1M · 5.8M · 3.5M'],
      ['--surface-2', revealed ? usd(earnings) : 'Earnings: ask the artist', 'shared with the label']
    ];
    tiles.forEach(([color, big, small], tile) => {
      const x = (tile % 2) * 800;
      const y = Math.floor(tile / 2) * 450;
      context.fillStyle = token(color);
      context.fillRect(x, y, 800, 450);
      context.fillStyle = tile === 3 ? token('--ink') : token('--accent-ink');
      context.font = `700 64px ${font}`;
      context.fillText(big, x + 48, y + 250);
      context.font = `500 30px ${font}`;
      context.fillText(small, x + 48, y + 310);
    });
    canvas.toBlob((blob) => { if (blob) deckUrl = URL.createObjectURL(blob); }, 'image/png');
  }
</script>

<svelte:window onkeydown={key} />
<svelte:head><title>Pulse · Afterglow campaign wrapped</title><meta name="description" content="Campaign Wrapped for Afterglow: views, the moment, where it traveled and earnings, generated on day 7." /></svelte:head>

<main class="pl-main pcw" data-anchor="pcw-main">
  <header class="pcw-head">
    <span class="pl-kicker">Campaign Wrapped · generated on day 7 from the same evidence as the dashboards</span>
    <h1>Afterglow, wrapped</h1>
  </header>

  {#if early}
    <section class="pl-panel pcw-early" data-anchor="pcw-early">
      <h2>Wrapped arrives on day 7</h2>
      <p>This campaign is on day 4. Pulse builds the recap on day 7 at 06:00 KST, once the Tokyo and LA waves have had time to land.</p>
      <a class="pl-btn" href="{base}/distribution">Back to the campaign</a>
    </section>
  {:else}
    <section class="pcw-story t-{tones[cards[index]]}" aria-roledescription="story" aria-label="Card {index + 1} of {cards.length}" data-anchor="pcw-story">
      <div class="pcw-bars" aria-hidden="true">{#each cards as card, position}<span><i class:done={position < index} class:now={position === index && !stopped} class:hold={position === index && stopped} style="animation-duration:{FRAME_MS}ms"></i></span>{/each}</div>
      {#key index}
        <div class="pcw-card" aria-live="polite">
          {#if cards[index] === 'views'}
            <span class="pcw-kicker">Seven days of Afterglow</span>
            <h2>{(views / 1_000_000).toFixed(1)}M views</h2>
            <div class="pr-eq big pcw-eq" aria-hidden="true">{#each Array(20) as _, bar}<i style="--i:{bar}"></i>{/each}</div>
          {:else if cards[index] === 'moment'}
            <span class="pcw-kicker">The moment that did it</span>
            <h2>A 0:24 fan edit, posted by 12 pages.</h2>
            <p>A Seoul fan page cut the hook at 21:40 KST. Every page that reposted it doubled the Tokyo wave the next morning.</p>
          {:else if cards[index] === 'travel'}
            <span class="pcw-kicker">Where it traveled</span>
            <h2>Seoul → Tokyo → LA</h2>
            <svg class="pcw-route" viewBox="0 0 260 190" role="img" aria-label="Seoul day 1, 9.1M views; Tokyo day 2, 5.8M; LA day 3, 3.5M">
              <path d="M70 40 Q 150 20 190 70 Q 150 150 60 150" pathLength="1" />
              {#each stops as stop}<g transform="translate({stop.x} {stop.y})"><circle r="8" /><text x="14" y="4">{stop.city} · {stop.views}</text></g>{/each}
            </svg>
          {:else}
            <span class="pcw-kicker">What it earned</span>
            <h2>{#if revealed}{usd(earnings)}{:else}<span aria-hidden="true">$ ••••</span><span class="visually-hidden">amount hidden</span>{/if}</h2>
            <button type="button" class="pcw-reveal" aria-pressed={revealed} onclick={() => (revealed = !revealed)}>{revealed ? 'Hide earnings' : 'Tap to reveal earnings'}</button>
            <p>Streaming, short-form royalties and the Maré sync, split by the signed sheet in the wallet.</p>
          {/if}
        </div>
      {/key}
      <button type="button" class="pcw-hit prev" aria-label="Previous card" onclick={() => (index = Math.max(0, index - 1))} onpointerdown={() => (held = true)} onpointerup={() => (held = false)} onpointerleave={() => (held = false)}></button>
      <button type="button" class="pcw-hit next" aria-label="Next card" onclick={() => (index = Math.min(cards.length - 1, index + 1))} onpointerdown={() => (held = true)} onpointerup={() => (held = false)} onpointerleave={() => (held = false)}></button>
      <div class="pcw-controls">
        <button type="button" class="pcw-pause" aria-pressed={paused} onclick={() => (paused = !paused)}>{paused ? 'Play' : 'Pause'}</button>
        <span>{index + 1} / {cards.length}</span>
      </div>
    </section>

    <div class="pcw-actions" data-anchor="pcw-actions">
      <button type="button" class="pl-btn primary" onclick={() => params.open({ share: 'label' })}>Share with the label</button>
      <button type="button" class="pl-btn" onclick={exportDeck}>Export as deck</button>
      {#if deckUrl}<a class="pl-btn" href={deckUrl} download="afterglow-wrapped-deck.png">Download deck (PNG)</a>{/if}
    </div>
  {/if}
</main>

{#if params.get('share') === 'label'}
  <Layer title="Share with Haneul Records" eyebrow="Campaign Wrapped · Afterglow" onclose={() => params.close(['share'])} width={520} anchor="pcw-share">
    <p>Sends the four cards and the evidence links (dashboards, fan-edit trail, split sheet) to the label's A&amp;R lead. Earnings are included only if you revealed them.</p>
    <ul class="st-brief"><li><b>Views</b> {(views / 1_000_000).toFixed(1)}M in 7 days</li><li><b>Moment</b> 0:24 fan edit · 12 pages</li><li><b>Travel</b> Seoul → Tokyo → LA</li><li><b>Earnings</b> {revealed ? usd(earnings) : 'not shared'}</li></ul>
    {#if sent}<p class="pl-banner info" role="status">Shared with Haneul Records · they'll see it in their Pulse inbox</p>{/if}
    {#snippet footer()}
      <button type="button" class="pl-btn primary" onclick={() => (sent = true)} disabled={sent}>{sent ? 'Shared' : 'Share'}</button>
      <button type="button" class="pl-btn" onclick={() => params.close(['share'])}>Cancel</button>
    {/snippet}
  </Layer>
{/if}
